### ISSUE TITLE
awesome_print is not in gemfile

### ISSUE THREAD

**Issue by anka-213** [Glutexo/memrise-to-beeminder#1]
You use `require 'awesome_print'` in [`beeminder.rb`](https://github.com/Glutexo/memrise-to-beeminder/blob/master/beeminder.rb#L3), but it is not used, and it is not mentioned in the gemfile. So the script refuses to run unless you install it manually or remove that line.

**Comment by Glutexo** [comment]
You are right, fixed.

Thank you for letting me know!
